// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwReturn-9]
	_ = x[KwEnd-10]
	_ = x[KwChar-11]
	_ = x[KwInt-12]
	_ = x[KwUnit-13]
	_ = x[KwString-14]
	_ = x[KwFloat-15]
	_ = x[KwIf-16]
	_ = x[KwThen-17]
	_ = x[KwElse-18]
	_ = x[KwStruct-19]
	_ = x[KwIs-20]
	_ = x[KwImportC-21]
	_ = x[Plus-22]
	_ = x[Minus-23]
	_ = x[Star-24]
	_ = x[Slash-25]
	_ = x[Equal-26]
	_ = x[EqualEqual-27]
	_ = x[Bang-28]
	_ = x[BangEqual-29]
	_ = x[Less-30]
	_ = x[LessEqual-31]
	_ = x[Greater-32]
	_ = x[GreaterEqual-33]
	_ = x[Arrow-34]
	_ = x[Modulo-35]
	_ = x[Pipe-36]
	_ = x[LogicalOr-37]
	_ = x[LogicalAnd-38]
	_ = x[Ampersand-39]
	_ = x[Caret-40]
	_ = x[Tilde-41]
	_ = x[PlusEqual-42]
	_ = x[MinusEqual-43]
	_ = x[StarEqual-44]
	_ = x[SlashEqual-45]
	_ = x[ModuloEqual-46]
	_ = x[CaretEqual-47]
	_ = x[PipeEqual-48]
	_ = x[AmpersandEqual-49]
	_ = x[PlusPlus-50]
	_ = x[MinusMinus-51]
	_ = x[LessLess-52]
	_ = x[GreaterGreater-53]
	_ = x[LeftParen-54]
	_ = x[RightParen-55]
	_ = x[LeftBrace-56]
	_ = x[RightBrace-57]
	_ = x[Comma-58]
	_ = x[Semicolon-59]
	_ = x[Colon-60]
	_ = x[Dot-61]
	_ = x[LeftBracket-62]
	_ = x[RightBracket-63]
	_ = x[EOF-64]
	_ = x[Error-65]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_returnkw_endkw_charkw_intkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 101, 107, 114, 120, 127, 136, 144, 149, 156, 163, 172, 177, 186, 190, 195, 199, 204, 209, 220, 224, 234, 238, 248, 255, 268, 273, 279, 283, 293, 304, 313, 318, 323, 333, 344, 354, 365, 377, 388, 398, 413, 422, 433, 442, 457, 467, 478, 488, 499, 504, 513, 518, 521, 533, 546, 549, 554}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
