// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwReturn-9]
	_ = x[KwEnd-10]
	_ = x[KwChar-11]
	_ = x[KwInt-12]
	_ = x[KwString-13]
	_ = x[KwFloat-14]
	_ = x[KwIf-15]
	_ = x[KwThen-16]
	_ = x[KwElse-17]
	_ = x[KwStruct-18]
	_ = x[KwIs-19]
	_ = x[Plus-20]
	_ = x[Minus-21]
	_ = x[Star-22]
	_ = x[Slash-23]
	_ = x[Equal-24]
	_ = x[EqualEqual-25]
	_ = x[Bang-26]
	_ = x[BangEqual-27]
	_ = x[Less-28]
	_ = x[LessEqual-29]
	_ = x[Greater-30]
	_ = x[GreaterEqual-31]
	_ = x[Arrow-32]
	_ = x[Modulo-33]
	_ = x[Pipe-34]
	_ = x[LogicalOr-35]
	_ = x[LogicalAnd-36]
	_ = x[Ampersand-37]
	_ = x[Caret-38]
	_ = x[Tilde-39]
	_ = x[PlusEqual-40]
	_ = x[MinusEqual-41]
	_ = x[StarEqual-42]
	_ = x[SlashEqual-43]
	_ = x[ModuloEqual-44]
	_ = x[CaretEqual-45]
	_ = x[PipeEqual-46]
	_ = x[AmpersandEqual-47]
	_ = x[PlusPlus-48]
	_ = x[MinusMinus-49]
	_ = x[LessLess-50]
	_ = x[GreaterGreater-51]
	_ = x[LeftParen-52]
	_ = x[RightParen-53]
	_ = x[LeftBrace-54]
	_ = x[RightBrace-55]
	_ = x[Comma-56]
	_ = x[Semicolon-57]
	_ = x[Colon-58]
	_ = x[Dot-59]
	_ = x[LeftBracket-60]
	_ = x[RightBracket-61]
	_ = x[EOF-62]
	_ = x[Error-63]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_returnkw_endkw_charkw_intkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_isplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 101, 107, 114, 120, 129, 137, 142, 149, 156, 165, 170, 174, 179, 183, 188, 193, 204, 208, 218, 222, 232, 239, 252, 257, 263, 267, 277, 288, 297, 302, 307, 317, 328, 338, 349, 361, 372, 382, 397, 406, 417, 426, 441, 451, 462, 472, 483, 488, 497, 502, 505, 517, 530, 533, 538}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
