// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwMut-9]
	_ = x[KwReturn-10]
	_ = x[KwEnd-11]
	_ = x[KwChar-12]
	_ = x[KwInt-13]
	_ = x[KwBool-14]
	_ = x[KwNull-15]
	_ = x[KwUnit-16]
	_ = x[KwString-17]
	_ = x[KwFloat-18]
	_ = x[KwIf-19]
	_ = x[KwThen-20]
	_ = x[KwElse-21]
	_ = x[KwStruct-22]
	_ = x[KwIs-23]
	_ = x[KwImportC-24]
	_ = x[KwLoop-25]
	_ = x[KwStop-26]
	_ = x[KwEnum-27]
	_ = x[Plus-28]
	_ = x[Minus-29]
	_ = x[Star-30]
	_ = x[Slash-31]
	_ = x[Equal-32]
	_ = x[EqualEqual-33]
	_ = x[Bang-34]
	_ = x[BangEqual-35]
	_ = x[Less-36]
	_ = x[LessEqual-37]
	_ = x[Greater-38]
	_ = x[GreaterEqual-39]
	_ = x[Arrow-40]
	_ = x[Modulo-41]
	_ = x[Pipe-42]
	_ = x[LogicalOr-43]
	_ = x[LogicalAnd-44]
	_ = x[Ampersand-45]
	_ = x[Caret-46]
	_ = x[Tilde-47]
	_ = x[PlusEqual-48]
	_ = x[MinusEqual-49]
	_ = x[StarEqual-50]
	_ = x[SlashEqual-51]
	_ = x[ModuloEqual-52]
	_ = x[CaretEqual-53]
	_ = x[PipeEqual-54]
	_ = x[AmpersandEqual-55]
	_ = x[PlusPlus-56]
	_ = x[MinusMinus-57]
	_ = x[LessLess-58]
	_ = x[GreaterGreater-59]
	_ = x[LeftParen-60]
	_ = x[RightParen-61]
	_ = x[LeftBrace-62]
	_ = x[RightBrace-63]
	_ = x[Comma-64]
	_ = x[Semicolon-65]
	_ = x[Colon-66]
	_ = x[Dot-67]
	_ = x[LeftBracket-68]
	_ = x[RightBracket-69]
	_ = x[Newline-70]
	_ = x[EOF-71]
	_ = x[Error-72]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_mutkw_returnkw_endkw_charkw_intkw_boolkw_nullkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importkw_loopkw_stopkw_enumplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketnewlineeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 98, 107, 113, 120, 126, 133, 140, 147, 156, 164, 169, 176, 183, 192, 197, 206, 213, 220, 227, 231, 236, 240, 245, 250, 261, 265, 275, 279, 289, 296, 309, 314, 320, 324, 334, 345, 354, 359, 364, 374, 385, 395, 406, 418, 429, 439, 454, 463, 474, 483, 498, 508, 519, 529, 540, 545, 554, 559, 562, 574, 587, 594, 597, 602}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
