set(AZIN_COMPILER_IS_GCC          OFF)
set(AZIN_COMPILER_IS_CLANG        OFF)
set(AZIN_COMPILER_IS_APPLECLANG   OFF)
set(AZIN_COMPILER_IS_CLANGCL      OFF)
set(AZIN_COMPILER_IS_MSVC         OFF)

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
    set(AZIN_COMPILER_IS_CLANGCL ON)
    set(_azin_comp_name "Clang-cl")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(AZIN_COMPILER_IS_GCC ON)
    set(_azin_comp_name "GCC")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(AZIN_COMPILER_IS_CLANG ON)
    set(_azin_comp_name "Clang")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
    set(AZIN_COMPILER_IS_APPLECLANG ON)
    set(_azin_comp_name "Apple Clang")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(AZIN_COMPILER_IS_MSVC ON)
    set(_azin_comp_name "MSVC")
else()
    set(_azin_comp_name "UNKNOWN")
    message(WARNING "Unknown compiler ID '${CMAKE_CXX_COMPILER_ID}'. Using fallback configuration.")
endif()

if(NOT CMAKE_CXX_COMPILER_VERSION)
    set(AZIN_COMPILER_VERSION "0.0.0")
else()
    set(AZIN_COMPILER_VERSION "${CMAKE_CXX_COMPILER_VERSION}")
endif()

message(STATUS "Compiler: ${_azin_comp_name} v${AZIN_COMPILER_VERSION}")