name: Linux

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang 22 (apt.llvm.org)
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release wget software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 all

      - name: Select Clang 22
        run: |
          echo "CC=clang-22" >> $GITHUB_ENV
          echo "CXX=clang++-22" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          output=$(./build/cli/azin version 2>&1)
          echo "$output"
          echo "$output" | grep -qi "azin 0.0.1"
