name: Linux

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: x64

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          output=$(./build/cli/azin version 2>&1)
          echo "$output"
          echo "$output" | grep -qi "azin 0.0.1"
