name: Windows

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build -j

      - name: Test
        run: |
          $output = (& .\build\apps\azc\Debug\azc.exe --version 2>&1) -join "`n"
          Write-Output $output
          
          if ($output -notmatch '0\.1\.0') {
            throw "Version string not found"
          }
